let books = [
  {
    isbn: 1000,
    name: "Harry Potter and the Chamber of Secrets",
    author: "J.K. Rowling",
    likes: 750,
    liked: false,
    price: 18.0,
    publishedYear: 1998,
    genre: "Fantasy",
    comments: [],
  },
  {
    isbn: 1001,
    name: "Daisy – Und all deine Geheimnisse werden mir gehören",
    author: "Melanie Raabe",
    likes: 1250,
    liked: true,
    price: 19.99,
    publishedYear: 2026,
    genre: "Thriller",
    comments: [],
  },
  {
    isbn: 1002,
    name: "Dunkel",
    author: "Ragnar Jónasson",
    likes: 980,
    liked: false,
    price: 14.5,
    publishedYear: 2020,
    genre: "Thriller",
    comments: [],
  },
  {
    isbn: 1003,
    name: "Eckstein – Die Kunst des Schiffbruchs",
    author: "Pascale Quiviger",
    likes: 1520,
    liked: true,
    price: 22.95,
    publishedYear: 2022,
    genre: "Fantasy",
    comments: [],
  },
  {
    isbn: 1004,
    name: "The Adventures of Sherlock Holmes",
    author: "Sir Arthur Conan Doyle",
    likes: 1300,
    liked: true,
    price: 16.75,
    publishedYear: 1892,
    genre: "Krimi",
    comments: [],
  },
  {
    isbn: 1005,
    name: "Twilight",
    author: "Stephenie Meyer",
    likes: 890,
    liked: false,
    price: 12.3,
    publishedYear: 2005,
    genre: "Romantik",
    comments: [],
  },
];
